apiVersion: v1
kind: ConfigMap
metadata:
  name: feline-html-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Feline Imagery (Config Map)</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
            }
            .container {
                background-color: #f5f5f5;
                padding: 20px;
                border-radius: 8px;
            }
            .form-group {
                margin-bottom: 15px;
            }
            label {
                display: block;
                margin-bottom: 5px;
                font-weight: bold;
            }
            select, input {
                width: 100%;
                padding: 8px;
                margin-bottom: 10px;
                border: 1px solid #ddd;
                border-radius: 4px;
            }
            button {
                background-color: #4CAF50;
                color: white;
                padding: 10px 20px;
                border: none;
                border-radius: 4px;
                cursor: pointer;
                font-size: 16px;
            }
            button:disabled {
                background-color: #cccccc;
            }
            .result {
                margin-top: 20px;
                padding: 20px;
                border: 1px solid #ddd;
                border-radius: 4px;
                display: none;
            }
            .error {
                color: red;
                display: none;
                margin: 10px 0;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Catsi</h1>
        </div>
    </body>
  </html>
