apiVersion: v1
kind: ConfigMap
metadata:
  name: feline-html-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Salary Predictor</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
            }
            .container {
                background-color: #f5f5f5;
                padding: 20px;
                border-radius: 8px;
            }
            .form-group {
                margin-bottom: 15px;
            }
            label {
                display: block;
                margin-bottom: 5px;
                font-weight: bold;
            }
            select, input {
                width: 100%;
                padding: 8px;
                margin-bottom: 10px;
                border: 1px solid #ddd;
                border-radius: 4px;
            }
            button {
                background-color: #4CAF50;
                color: white;
                padding: 10px 20px;
                border: none;
                border-radius: 4px;
                cursor: pointer;
                font-size: 16px;
            }
            button:disabled {
                background-color: #cccccc;
            }
            .result {
                margin-top: 20px;
                padding: 20px;
                border: 1px solid #ddd;
                border-radius: 4px;
                display: none;
            }
            .error {
                color: red;
                display: none;
                margin: 10px 0;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Salary Predictor</h1>
            <form id="predictionForm">
                <div class="form-group">
                    <label for="experience_level">Experience Level:</label>
                    <select id="experience_level" required>
                        <option value="0">Entry Level (EN)</option>
                        <option value="1">Mid Level (MI)</option>
                        <option value="2">Senior (SE)</option>
                        <option value="3">Executive (EX)</option>
                    </select>
                </div>

                <div class="form-group">
                    <label for="company_size">Company Size:</label>
                    <select id="company_size" required>
                        <option value="0">Small (S)</option>
                        <option value="1">Medium (M)</option>
                        <option value="2">Large (L)</option>
                    </select>
                </div>

                <div class="form-group">
                    <label>Employment Type:</label>
                    <select id="employment_type" required>
                        <option value="0">Full Time</option>
                        <option value="1">Part Time</option>
                    </select>
                </div>

                <div class="form-group">
                    <label>Job Title:</label>
                    <select id="job_title" required>
                        <option value="other">Other</option>
                        <option value="engineer">Data Engineer</option>
                        <option value="manager">Data Manager</option>
                        <option value="scientist">Data Scientist</option>
                        <option value="ml">Machine Learning Engineer</option>
                    </select>
                </div>

                <button type="submit">Predict Salary</button>
            </form>

            <div id="error" class="error">
                An error occurred. Please try again.
            </div>

            <div id="result" class="result">
                <h2>Predicted Salary</h2>
                <p id="salary"></p>
            </div>
        </div>

        <script>
            document.getElementById('predictionForm').addEventListener('submit', async (e) => {
                e.preventDefault();
                
                const experience = document.getElementById('experience_level').value;
                const companySize = document.getElementById('company_size').value;
                const employmentType = document.getElementById('employment_type').value;
                const jobTitle = document.getElementById('job_title').value;

                // Reset UI states
                document.querySelector('button').disabled = true;
                document.getElementById('error').style.display = 'none';
                document.getElementById('result').style.display = 'none';

                // Prepare the data object
                const data = {
                    "experience_level_encoded": parseFloat(experience),
                    "company_size_encoded": parseFloat(companySize),
                    "employment_type_PT": parseInt(employmentType),
                    "job_title_Data_Engineer": jobTitle === "engineer" ? 1 : 0,
                    "job_title_Data_Manager": jobTitle === "manager" ? 1 : 0,
                    "job_title_Data_Scientist": jobTitle === "scientist" ? 1 : 0,
                    "job_title_Machine_Learning_Engineer": jobTitle === "ml" ? 1 : 0
                };

                try {
                    const response = await fetch('/predict', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                        },
                        body: JSON.stringify(data)
                    });

                    if (!response.ok) throw new Error('Prediction failed');

                    const result = await response.json();
                    document.getElementById('salary').textContent = 
                        `$${Math.round(result["Salary (USD)"]).toLocaleString()}`;
                    document.getElementById('result').style.display = 'block';
                } catch (err) {
                    console.error('Error:', err);
                    document.getElementById('error').style.display = 'block';
                } finally {
                    document.querySelector('button').disabled = false;
                }
            });
        </script>
    </body>
    </html>
