# grafana-credentials.yaml
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
type: Opaque
data:
  admin-user: YWFhCg==  # aaa (base64 encoded)
  admin-password: ZW50ZXJzZXNhbWUK  # opensesame (enter base64 encoded)